name: FKS App CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install TA-Lib dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          rm -rf ta-lib ta-lib-0.4.0-src.tar.gz
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff mypy
          
      - name: Lint with ruff
        run: ruff check src/
        continue-on-error: true
        
      - name: Type check with mypy
        run: mypy src/
        continue-on-error: true
        
      - name: Run tests
        run: pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: fks_app
          name: fks-app-coverage
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t fks_app:latest .
        
      - name: Test Docker image
        run: |
          docker run -d --name fks_app_test -p 8002:8002 fks_app:latest
          sleep 10
          curl -f http://localhost:8002/health || exit 1
          docker stop fks_app_test
