name: FKS Web CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-web-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-web-
            
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django>=5.2.7
          pip install pytest pytest-django pytest-cov ruff mypy
          
      - name: Install Node.js dependencies
        run: |
          if [ -f package.json ]; then npm install; fi
          
      - name: Lint with ruff
        run: ruff check src/
        continue-on-error: true
        
      - name: Type check with mypy
        run: mypy src/
        continue-on-error: true
        
      - name: Run tests
        run: pytest tests/ -v --cov=src --cov-report=xml --cov-report=term
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: fks_web
          name: fks-web-coverage
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t fks_web:latest .
        
      - name: Test Docker image
        run: |
          docker run -d --name fks_web_test -p 3001:3001 fks_web:latest
          sleep 15
          curl -f http://localhost:3001/ || exit 1
          docker stop fks_web_test
