name: FKS Ninja CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
        
      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        
      - name: Format check
        run: dotnet format --verify-no-changes --no-restore
        continue-on-error: true
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: docker build -t fks_ninja:latest .
        
      - name: Test Docker image
        run: |
          docker run -d --name fks_ninja_test -p 8005:8005 fks_ninja:latest
          sleep 10
          curl -f http://localhost:8005/health || exit 1
          docker stop fks_ninja_test
