name: 🔴 Critical Bug
description: Report a critical issue blocking development or deployment
title: "[CRITICAL] "
labels: ["🔴 critical", "bug"]
assignees:
  - nuniesmith

body:
  - type: markdown
    attributes:
      value: |
        ## Critical Bug Report
        Use this template for issues that **block development or deployment**.
        
        **Examples**: Test failures, security vulnerabilities, build errors
        
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this affect?
      options:
        - Import Errors / Dependencies
        - Security Vulnerability
        - Test Failures
        - Database / Migration
        - Docker / Deployment
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's broken and why is it critical?
      placeholder: "Example: 20 tests failing due to import errors from legacy 'config' module"
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is blocked by this issue?
      placeholder: "Example: Cannot validate code changes, blocks deployment"
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run `pytest tests/unit/test_trading/`
        2. See import errors: `from config import SYMBOLS`
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: |
        1. Create `framework/config/constants.py`
        2. Update imports to use Django settings
        3. Run tests to verify
    validations:
      required: false
  
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - Low (< 1 day)
        - Medium (1-3 days)
        - High (> 3 days)
    validations:
      required: true
