name: ✨ Feature Implementation
description: Implement a new feature or complete a stub
title: "[FEATURE] "
labels: ["✨ feature", "enhancement"]
assignees:
  - nuniesmith

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Implementation Request
        Use this for new features or completing stubbed implementations.
        
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - FKS Intelligence / RAG
        - Celery Tasks (Trading)
        - Web UI / Templates
        - Testing / CI/CD
        - API / Backend
        - Other
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What needs to be implemented?
      placeholder: "Example: Implement market_data_sync_task to fetch OHLCV data from Binance"
    validations:
      required: true
  
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know it's done?
      placeholder: |
        - [ ] Task fetches data for all configured symbols
        - [ ] Data stored in TimescaleDB hypertable
        - [ ] Unit tests pass
        - [ ] Integration test with Binance API
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical (blocks other work)
        - P1 - High (core feature)
        - P2 - Medium (improvement)
        - P3 - Low (nice-to-have)
    validations:
      required: true
  
  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - Low (< 1 day)
        - Medium (1-3 days)
        - High (> 3 days)
    validations:
      required: true
  
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What must be completed first?
      placeholder: "Example: Requires #42 (fix import errors) to be resolved"
