name: Create Phased Issues

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process for phased implementation'
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-phased-issues:
    name: Create Phased Implementation Issues
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, '🚀 phased-implementation')) ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get issue details
        id: issue
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ISSUE_NUMBER="${{ inputs.issue_number }}"
          else
            ISSUE_NUMBER="${{ github.event.issue.number }}"
          fi

          # Get issue data
          ISSUE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER")

          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

          # Extract key information using jq
          TITLE=$(echo "$ISSUE_DATA" | jq -r '.title // "Unknown Title"')
          BODY=$(echo "$ISSUE_DATA" | jq -r '.body // ""')
          AREA=$(echo "$BODY" | grep -A 1 "Implementation Area" | tail -n 1 | sed 's/^- //' | sed 's/^.*: //' || echo "General")
          PHASES=$(echo "$BODY" | grep -A 1 "Number of Phases" | tail -n 1 | sed 's/^- //' | sed 's/".*"/ /' | cut -d' ' -f1 || echo "6-10")

          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "area=$AREA" >> $GITHUB_OUTPUT
          echo "phases=$PHASES" >> $GITHUB_OUTPUT

      - name: Generate phase breakdown
        id: phases
        run: |
          AREA="${{ steps.issue.outputs.area }}"
          PHASE_COUNT="${{ steps.issue.outputs.phases }}"

          # Determine number of phases based on selection
          case "$PHASE_COUNT" in
            "3-5")
              NUM_PHASES=4
              ;;
            "6-10")
              NUM_PHASES=8
              ;;
            "11-15")
              NUM_PHASES=12
              ;;
            "16+")
              NUM_PHASES=16
              ;;
            *)
              NUM_PHASES=8
              ;;
          esac

          echo "num_phases=$NUM_PHASES" >> $GITHUB_OUTPUT

          # Store phases as environment variable for next step
          echo "PHASES_JSON<<EOF" >> $GITHUB_ENV
          echo "$PHASES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create phased issues
        run: |
          ISSUE_NUMBER="${{ steps.issue.outputs.issue_number }}"
          AREA="${{ steps.issue.outputs.area }}"
          NUM_PHASES="${{ steps.phases.outputs.num_phases }}"

          echo "Creating $NUM_PHASES phased issues for: $AREA"

          # Create issues for each phase
          echo "$PHASES_JSON" | jq -c '.[]' | while read -r phase; do
            TITLE=$(echo "$phase" | jq -r '.title')
            DESCRIPTION=$(echo "$phase" | jq -r '.description')
            LABELS=$(echo "$phase" | jq -r '.labels | join(",")')

            # Create the issue
            ISSUE_BODY="## Phase Description
          $DESCRIPTION

          ## Parent Issue
          Part of phased implementation: #${ISSUE_NUMBER}

          ## Dependencies
          - Requires completion of previous phases
          - Blocked by: [List any specific dependencies]

          ## Acceptance Criteria
          - [ ] Phase objectives completed
          - [ ] Code reviewed and approved
          - [ ] Tests passing
          - [ ] Documentation updated
          - [ ] No regressions introduced

          ## Implementation Notes
          [Add specific implementation details, code changes, or considerations]"

            # Create issue via API
            RESPONSE=$(curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -d "{
                \"title\": \"$TITLE\",
                \"body\": \"$ISSUE_BODY\",
                \"labels\": [\"${LABELS}\"]
              }" \
              "https://api.github.com/repos/${{ github.repository }}/issues")

            NEW_ISSUE_NUMBER=$(echo "$RESPONSE" | jq -r '.number')
            echo "Created issue #$NEW_ISSUE_NUMBER: $TITLE"
          done

      - name: Update parent issue
        run: |
          ISSUE_NUMBER="${{ steps.issue.outputs.issue_number }}"
          NUM_PHASES="${{ steps.phases.outputs.num_phases }}"

          # Add comment to parent issue
          COMMENT="## 🚀 Phased Implementation Created

          **Generated $NUM_PHASES implementation phases** for this feature request.

          ### Next Steps:
          1. Review the created phase issues
          2. Adjust priorities and assignments as needed
          3. Start with Phase 1 implementation
          4. Use the project board to track progress

          ### Phase Management:
          - Each phase has specific acceptance criteria
          - Phases are designed to be completed sequentially
          - All phases must pass before closing this parent issue

          The phased issues have been automatically added to the project board for tracking."

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"body\": \"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"

      - name: Notify phased issue creation
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 Phased Issues Created"
          description: |
            **Parent Issue:** #${{ steps.issue.outputs.issue_number }}
            **Area:** ${{ steps.issue.outputs.area }}
            **Phases Created:** ${{ steps.phases.outputs.num_phases }}

            Implementation phases have been automatically generated and added to the project board.
          color: ${{ job.status == 'success' && 0x00ff00 || 0xff0000 }}
          username: FKS Issue Bot