name: Markdown Linting

on:
  push:
    branches: [main, develop]
    paths:
      - '**.md'
      - '.markdownlintrc'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - '**.md'
      - '.markdownlintrc'
      - '.github/workflows/markdown-lint.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  markdown-lint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: |
          echo "🔍 Running markdown linter..."
          markdownlint 'docs/**/*.md' '*.md' || {
            echo ""
            echo "❌ Markdown linting failed!"
            echo "To fix locally, run:"
            echo "  npm install -g markdownlint-cli"
            echo "  markdownlint --fix 'docs/**/*.md' '*.md'"
            exit 1
          }
          echo "✅ All markdown files passed linting!"

      - name: Comment PR on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Markdown linting failed!**\n\nPlease fix the errors by running:\n```bash\nnpm install -g markdownlint-cli\nmarkdownlint --fix "docs/**/*.md" "*.md"\n```\n\nThen commit and push the fixes.'
            })
